package com.nsn.dubbo.dubboinvoker.dal.mapper;

import com.nsn.dubbo.dubboinvoker.dal.po.InvokeLog;
import com.nsn.dubbo.dubboinvoker.dal.po.InvokeLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InvokeLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOKE_LOG
     *
     * @mbggenerated
     */
    int countByExample(InvokeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOKE_LOG
     *
     * @mbggenerated
     */
    int deleteByExample(InvokeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOKE_LOG
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOKE_LOG
     *
     * @mbggenerated
     */
    int insert(InvokeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOKE_LOG
     *
     * @mbggenerated
     */
    int insertSelective(InvokeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOKE_LOG
     *
     * @mbggenerated
     */
    List<InvokeLog> selectByExample(InvokeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOKE_LOG
     *
     * @mbggenerated
     */
    InvokeLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOKE_LOG
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") InvokeLog record, @Param("example") InvokeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOKE_LOG
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") InvokeLog record, @Param("example") InvokeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOKE_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InvokeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INVOKE_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InvokeLog record);
}